version: '3.7'

services:
  web:
    build: ./backend
    command: python run.py run -h 0.0.0.0
    volumes:
        - ./backend:/usr/src/app
    ports:
        - 5000:5000
    env_file:
        - ./.env.dev