version: '3.7'

services:
    web:
        build: ./backend
        command: gunicorn --bind 0.0.0.0:5000 run:app
        expose:
            - 5000
        env_file:
            - ./.env.prod
    scraper:
        build: ./scrapers/production
        command: scrapyrt -i 0.0.0.0
        ports:
            - 9080:9080
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web