FROM python:3.8.1-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
apt-get install -y --no-install-recommends gcc

# should create non-root user somewhere here

COPY . /usr/src/app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn==20.0.4