FROM python:3.7-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
apt-get install -y --no-install-recommends gcc

# should create non-root user somewhere here
COPY . /usr/src/app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt 
RUN python setup.py

EXPOSE 9080